### ISSUE TITLE
Add better definition of year selection for calendar filters

### ISSUE THREAD

**Issue by saschaben** [ilios/user-guide#12]
Right now, in https://iliosproject.gitbooks.io/ilios-user-guide/content/calendar_search_filter_options.html, we don't clarify the specific use for the academic year drop-down in the filters, which has caused some confusion for users. 

We should add an additional screenshot pointing it out, and explain that this dropdown only and specifically controls the lists of courses and cohorts available for filtering --- not the display of information on the calendar itself, which will always show events for all available stretches of time.

**Comment by dartajax** [comment]
I will take care of this and then close the issue once you approve the additions.  Cool?

**Comment by dartajax** [comment]
I added a new section called "Load Filters Based On Academic Year & School" to the page.  Can you see if it works for you when you get a chance?

**Comment by saschaben** [comment]
Courses and Session Types associated with the selected Academic Year (and School if you have access to more than one school) are available for selection by using the Academic Year Selector shown below. The School Selector (if applicable) is to the right of the Academic Year Selector. This does not necessarily mean that the Course doesn't extend forward or backwards into a different Calendar or Educational year. This drop-down only and specifically controls the lists of courses and cohorts available for filtering --- not the display of information on the calendar itself, which will always show events for all available stretches of time.

**Comment by dartajax** [comment]
Updated and gonna close the ticket.
