### ISSUE TITLE
Update Rollover documentation

### ISSUE THREAD

**Issue by saschaben** [ilios/user-guide#13]
Currently, the rollover section does not specify how to roll over a course into the current year versus a different academic year, or inot anopther year where a course of the same name already exists. It needs to. Explanation of how the changing of a course name will alter the target year list is needed.

**Comment by dartajax** [comment]
I added a new section.  Please review when you get the chance and if it meets muster, let me know if I should close this issue.

https://iliosproject.gitbooks.io/ilios-user-guide/content/course_rollover.html

**Comment by saschaben** [comment]
Still needs some work. 2nd paragraph, which now reads:
> Courses can "rolled over" into a different (future) academic year or they can remain in the current academic year. This could be if a Course is offered in the Fall and then again in the Spring for example. 

should be changed to:
> Courses can "rolled over" into a different time period and/or academic year. So a course given in 2015-16 could be "rolled over" into 2016-17, or into the same year with a different start date. This could be if a Course is offered in the Fall and then again in the Spring for example. 

> A rolled over course must have a unique title; if a course with a duplicate title already exists in your target academic, year, the dropdown list shown will notify you of this. To place your course in a year where a duplicate exists, just alter the course title as shown below, in the course rollover form.

....and then add a screenshot to illustrate.

**Comment by dartajax** [comment]
Those things are addressed in the new section added below ...

### Roll Course Over Into Future Year
