### ISSUE TITLE
Figure out how to host the images in the repository

### ISSUE THREAD

**Issue by jrjohnson** [ilios/user-guide#2]
Right now all of the images are in imagur and not actually linked to the binaries in the repo.  We should either link to the repo images through a relative path or institute a build process that puts them somewhere predictable.

**Comment by Trott** [comment]
If the only place this is intended to live is GitHub, you can link to the binaries in the repo through a full path (e.g., https://raw.githubusercontent.com/ilios/user-guide/master/Images/AddMeSH1.JPG) at least as a stop gap measure.
